# Generated by Django 3.0.3 on 2020-02-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_remove_app_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('size', models.BigIntegerField(default=0)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
            ],
        ),
    ]
