# Generated by Django 3.0.3 on 2020-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
