# Generated by Django 3.0.3 on 2020-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=10)),
                ('secret_key', models.CharField(max_length=10)),
                ('total_file', models.PositiveIntegerField(default=0)),
                ('total_memory', models.BigIntegerField(default=0)),
            ],
        ),
    ]
